import Head from 'next/head'
import React from 'react'
import Header from "../../../globalComponents/Header/Header"
import LeftSidebar from '../../Home/components/Sidebars/Left-Sidebar/LeftSidebar'
import RightSideBar from '../../Home/components/Sidebars/Right-Sidebar/RightSideBar'

interface Props {
    children: React.ReactNode
}


const CommunityLayout = ({children}:Props) => {
    return (
      <div>
          <div className='w-full max-h-screen overflow-hidden'>
          <Head>
              <title>Reddit 2.0</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
  
          <Header />
          {/* <LeftSidebar /> */}
          {children}
          {/* <RightSideBar /> */}
  
          </div>
      </div>
    )
  }
  
export default CommunityLayout