import Head from 'next/head'
import React from 'react'
import Header from '../Header/Header'

interface Props {
    children: React.ReactNode
}

const HomePageLayout = ({children}:Props) => {
  return (
    <div className='w-full max-h-screen overflow-hidden'>
        <Head>
            <title>Reddit 2.0</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        {children}
    </div>
  )
}

export default HomePageLayout