import React, {useEffect , useState} from 'react'
import { useRouter } from "next/router"
import SubredditPageLayout from '../../components/Layouts/SubredditPageLayout'
import { doc, getDoc } from 'firebase/firestore'
import { auth, db } from '../../firebaseConfig'
import { useDispatch, useSelector } from 'react-redux'
import { setSubreddit } from '../../redux/subredditSlice'
import RightBar from '../../components/Sidebars/RightBar/RightBar'
import TopSection from '../../components/Subbredit/SubredditHomePage/TopSection/TopSection'
import { useAuthState } from 'react-firebase-hooks/auth'
import Tabs from '../../components/Subbredit/SubredditHomePage/TopSection/Tabs'


const SubredditHomePage = () => {
  const [user] = useAuthState(auth)
  const [subredditState, setSubredditState] = useState<any[]>([])
    
  
  const dispatch = useDispatch();
  const router = useRouter()
  const { id } = router.query
    
  const fetchSubreddit = async () => {
    const subredditRef = doc(db, "subreddits", id as string)
    const subredditDocSnap = await getDoc(subredditRef)
    setSubredditState([subredditDocSnap.data()])
    dispatch(setSubreddit( subredditDocSnap.data() ))
  }


  useEffect(() => {
    if(router.isReady) {
      fetchSubreddit()
    }
  }, [router.isReady])
    
  return (
    <SubredditPageLayout> 
      <main
        className='w-full h-[92vh] mt-[7vh] bg-red-200 flex flex-col justify-start items-center overflow-x-hidden overflow-y-scroll'
      >
       <TopSection />
       <h1 onClick={() => console.log(subredditState)}> LOG subreddit State  </h1>
       <Tabs />

      

      <div className='bg-red-400'>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>

      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>

      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p><p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>

      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>

      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      <p>properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties properties </p>
      </div>





      </main>
    </SubredditPageLayout>
  )
}

export default SubredditHomePage